openapi: 3.0.0
info:
  title: Products-Service
  version: 1.0.0
paths:
  /products:
    get:
      summary: Returns a list of products depending on the categoryId sent
      parameters:
        - in: query
          name: categoryId
          schema:
            type: number
            description: category id to retrieve the products from
            example: 1
        - in: query
          name: page
          schema:
            type: number
            description: the page number requesting the products
            example: 1
        - in: query
          name: limit
          schema:
            type: number
            description: the maximum number of products in the requested page, if it's not defined, the default is 25
            example: 25
      responses:
        '200':
          description: A JSON array of products having the same category, each product in this array has the information of the provider with the least price
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Product'
        '400':
          description: Indicates a bad request as a result of input validator error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
  /toggleFeatured/{id}:
    patch:
      summary: Toggles (set/unset) a product as featured inside its category
      parameters:
        - in: path
          name: id 
          required: true
          schema:
            type: number
            example: 1
          description: The id of the product to set/unset featured status
      responses:
        '204':
          description: The toggle operation was executed successfully
        '400':
          description: Indicates a bad request as a result of input validator error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: The toggle operation failed because the id sent wasn't found in the database
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        productName:
          type: string
        imageURI:
          type: string
        featured:
          type: boolean
        category:
          type: object
          $ref: '#/components/schemas/Category'
        ProductProviders:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/ProductProvider'    
    Category:
      type: object
      properties:
        id:
          type: number
        categoryName:
          type: string
    Provider:
      type: object
      properties:
        id:
          type: string
        providerName:
          type: string
          
    ProductProvider:
      type: object
      properties:
        provider:
          type: object
          $ref: '#/components/schemas/Provider'
        price:
          type: number
        available:
          type: boolean
    ResponseMessage:
      type: object
      properties:
        message:
          type: string
